Utiliser les composants GeojsonLayer pour afficher les styles
AgenceBio/cartobio-front pull request #144
Opened 2023-05-25 16:05 UTC by jillro

2023-05-30 08:23 UTC, jillro commented
Bloquée par https://github.com/AgenceBio/cartobio-front/pull/145

2023-05-30 10:23 UTC, thom4parisot commented on src/components/Map/GeojsonLayer.vue
> +<script>
Il y a une raison particulière, de passer du `<script setup>` à l'API Options de Vue ?

2023-05-30 10:45 UTC, jillro commented on src/components/Map/GeojsonLayer.vue
> +<script>
Oui ! Impossible d'accéder à l'élément parent dans l'API Composition. Or j'ai besoin aux sibilings (donc au parent) pour gérer l'ordre des layers.

2023-05-30 13:43 UTC, thom4parisot commented on src/components/Map/GeojsonLayer.vue
> +<script>
Oh je comprends mieux, merci :-)

T'avais essayé avec [`useSlots()`](https://vuejs.org/api/sfc-script-setup.html#useslots-useattrs) et [`defineExpose()`](https://vuejs.org/api/sfc-script-setup.html#defineexpose) ?

2023-05-30 14:32 UTC, jillro commented on src/components/Map/GeojsonLayer.vue
> +<script>
Oui, l'autre approche aurait été de faire un useSlots au niveau du MapContainer et ensuite faire que le MapContainer provide l'ordre des layers, et je t'avoue que je ne sais plus pourquoi j'ai exclu cette option mais je crois qu'il y avait une raison :/

2023-05-30 14:45 UTC, thom4parisot commented on src/components/Map/GeojsonLayer.vue
> +<script>
Ça roule :)

2023-05-31 08:19 UTC, thom4parisot requested changes
C'est beaucoup plus lisible avec les rayures 🙂 C'est cool de fonctionner purement par composant, merci !

Avec ce changement, je constate qu'on a perdu ces interactions :

- le survol d'une parcelle ne la surligne pas la parcelle dans le tableau
- le survol d'une parcelle dans le tableau ne la surligne plus sur la carte
- le clic sur une parcelle ne l'active pas dans le tableau
- le clic sur une parcelle de tableau ne l'active pas sur la carte

2023-06-01 08:38 UTC, jillro commented
> C'est beaucoup plus lisible avec les rayures slightly_smiling_face C'est cool de fonctionner purement par composant, merci !
> 
> Avec ce changement, je constate qu'on a perdu ces interactions :
> 
>     * le survol d'une parcelle ne la surligne pas la parcelle dans le tableau
> 
>     * le survol d'une parcelle dans le tableau ne la surligne plus sur la carte
> 
>     * le clic sur une parcelle ne l'active pas dans le tableau
> 
>     * le clic sur une parcelle de tableau ne l'active pas sur la carte

Yes, merci de l'avoir vu, c'est résolu par le dernier commit :)

2023-06-01 09:26 UTC, thom4parisot commented
Super, bien vu :)

2023-06-01 09:26 UTC, merged